services:
  graphprocessorapi:
    image: vibecoderhex/graphprocessorapi:latest
    build:
      context: .
      dockerfile: ./GraphProcessorAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=graphProcessor;Username=vibecoderhex;Password=azsxdcQ1!
      - JwtParams__SecretKey=qwertyuiop1234567890Q1!zxcvbnm,./;'[]'
      - JwtParams__Issuer=VibeCoderHex
      - JwtParams__Audience=VibeCoderHexUsers
    restart: unless-stopped
  
  graphprocessorfrontend:
    image: vibecoderhex/graphprocessorfrontend:latest
    build:
      context: ./GraphProcessorFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: vibecoderhex
      POSTGRES_PASSWORD: azsxdcQ1!
      POSTGRES_DB: graphProcessor
    ports:
      - "5432:5432"
    volumes:
      - gp_pgdata:/var/lib/postgresql/data

volumes:
  gp_pgdata:  