services:
  graphprocessorapi:
    image: vibecoderhex/graphprocessorapi:latest
    build:
      context: .
      dockerfile: ./GraphProcessorAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${EFCORE_CONNECTIONSTRING}
      - JwtParams__SecretKey=${JWTPARAMS_SECRET_KEY}
      - JwtParams__Issuer=${JWTPARAMS_ISSUER}
      - JwtParams__Audience=${JWTPARAMS_AUDIENCE}
    restart: unless-stopped
  
  graphprocessorfrontend:
    image: vibecoderhex/graphprocessorfrontend:latest
    build:
      context: ./GraphProcessorFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - gp_pgdata:/var/lib/postgresql/data

volumes:
  gp_pgdata:  